In [2]:
import numpy as np
import pandas as pd

pd.options.display.max_columns = 999
pd.options.display.float_format = "{:.2f}".format
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [8]:
data = pd.read_csv ("dataset_with_sentiment.csv")
data.head()

,Unnamed: 0,score,self_text,subreddit,created_time,author_name,controversiality,ups,downs,user_is_verified,post_created_time,clean_text,side,sentiment,sentiment_score
0,0,134,Which is also ridiculous because we literally ...,worldnews,2025-04-27 23:59:11,Cutapotamus,0,134,0,True,2025-04-27 22:33:44,Which is also ridiculous because we literally ...,Unclear,Negative,0.71
1,1,1,Because Israel will kill everyone inside? We w...,IsraelPalestine,2025-04-27 23:58:56,MrNewVegas123,0,1,0,True,2025-04-27 09:42:09,Because Israel will kill everyone inside? We w...,Palestine,Negative,0.91
2,2,1,There were a lot of big protests hence why the...,IsraelPalestine,2025-04-27 23:58:31,Best-Anxiety-6795,0,1,0,True,2025-04-27 18:36:57,There were a lot of big protests hence why the...,Unclear,Negative,0.58
3,3,5,Just because the administration and echo chamb...,worldnews,2025-04-27 23:57:58,Interesting-Type-908,0,5,0,True,2025-04-27 22:33:44,Just because the administration and echo chamb...,Unclear,Negative,0.77
4,4,1,"Good for you, and boo on your friends/acquaint...",IsraelPalestine,2025-04-27 23:56:51,cloudedknife,0,1,0,True,2025-04-27 21:39:55,"Good for you, and boo on your friends/acquaint...",Palestine,Negative,0.67

> ### Drop the Unclear side because we want to focus at Israel and Palestine issue

In [9]:
# Drop rows where the 'sentiment' column is 'Unclear'
data = data[data['side'] != 'Unclear'].reset_index(drop=True)

# Display the updated DataFrame
data.head()

,Unnamed: 0,score,self_text,subreddit,created_time,author_name,controversiality,ups,downs,user_is_verified,post_created_time,clean_text,side,sentiment,sentiment_score
0,1,1,Because Israel will kill everyone inside? We w...,IsraelPalestine,2025-04-27 23:58:56,MrNewVegas123,0,1,0,True,2025-04-27 09:42:09,Because Israel will kill everyone inside? We w...,Palestine,Negative,0.91
1,4,1,"Good for you, and boo on your friends/acquaint...",IsraelPalestine,2025-04-27 23:56:51,cloudedknife,0,1,0,True,2025-04-27 21:39:55,"Good for you, and boo on your friends/acquaint...",Palestine,Negative,0.67
2,6,1,A Gaza-West Bank corridor has been a part of e...,IsraelPalestine,2025-04-27 23:55:23,MrNewVegas123,0,1,0,True,2025-04-27 13:40:05,A Gaza-West Bank corridor has been a part of e...,Palestine,Negative,0.81
3,7,1,"They'll definitely try after the war ends, and...",IsraelPalestine,2025-04-27 23:54:50,ZachorMizrahi,0,1,0,True,2025-04-26 17:23:37,"They'll definitely try after the war ends, and...",Israel,Negative,0.65
4,9,1,Hamas is an ideologically motivated militant g...,IsraelPalestine,2025-04-27 23:53:14,MrNewVegas123,0,1,0,True,2025-04-27 09:42:09,Hamas is an ideologically motivated militant g...,Neutral,Negative,0.75

In [10]:
filtered_df = data[(data["side"] == "Unclear") & (data["sentiment"] == "Negative")]
filtered_df.head()

Empty DataFrame
Columns: [Unnamed: 0, score, self_text, subreddit, created_time, author_name, controversiality, ups, downs, user_is_verified, post_created_time, clean_text, side, sentiment, sentiment_score]
Index: []

> ### Drop another columns that are not being used

In [11]:
# List of columns to drop
columns_to_drop = ['sentiment_score', 'controversiality', 'ups', 'downs', 'user_is_verified', 'score']

# Drop the specified columns
data = data.drop(columns=columns_to_drop)

# Display the updated DataFrame
data.head()

#save it to another csv file
data.to_csv('final_dataset_israel-palestine.csv', index=False)

> ### Fix the Attention clean_text

In [12]:
# Set the maximum column width to None to show full text
pd.set_option('display.max_colwidth', None)
filtered_df = data[data["clean_text"].str.contains("Fuck Israel")]
filtered_df.head()

,Unnamed: 0,self_text,subreddit,created_time,author_name,post_created_time,clean_text,side,sentiment
4119,9929,Fuck Israel and all its supporters 🖕🏻🖕🏻🖕🏻🖕🏻,PublicFreakout,2025-04-24 02:09:59,spicytinyghost,2025-04-23 23:31:19,Fuck Israel and all its supporters 🖕🏻🖕🏻🖕🏻🖕🏻,Palestine,Negative
4160,10052,Fuck Israel,PublicFreakout,2025-04-24 01:19:03,Macho_Ric_Hogan,2025-04-23 23:31:19,Fuck Israel,Palestine,Negative
7539,18627,Fuck Israel,PublicFreakout,2025-04-21 01:37:43,Macho_Ric_Hogan,2025-04-20 13:46:04,Fuck Israel,Palestine,Negative
8209,20281,Fuck Israel,PublicFreakout,2025-04-20 15:20:13,Goomancy,2025-04-20 13:46:04,Fuck Israel,Palestine,Negative
8220,20311,Fuck Israel,PublicFreakout,2025-04-20 15:08:38,ArcHacks,2025-04-20 13:46:04,Fuck Israel,Palestine,Negative

> ### Put it to "Moderator" Side

In [13]:
import pandas as pd

# Sample DataFrame (replace this with your actual data loading step)
# Example:
# data = pd.read_csv("your_dataset.csv")

# Keywords to detect moderator-related messages
moderation_keywords = [
    "Your content has been removed",  # Removal notices
    "Please read our [rules]",        # Rule violation warnings
    "violating **[Rule",              # Rule violation notices
    "Looks like this thread is getting a lot of attention",  # Civility reminders
    "I am a bot, and this action was performed automatically",  # Bot signatures
    "[Please read this warning!]",    # Moderator warnings
    "Kindly review the subreddit rules",  # Rule reminders
    "All parties share unconditional support for Israel"  # Specific moderator message
]

# Function to detect moderator-related messages
def is_mod_removal(text):
    """
    Checks if the text contains any of the moderation keywords.
    Returns True if it's a moderator message, False otherwise.
    """
    return any(keyword in text for keyword in moderation_keywords)

# Apply the function to create/update the 'is_mod_message' column
data['is_mod_message'] = data['clean_text'].apply(is_mod_removal)

# Update the 'side' column to 'Moderator' for moderator-related messages
data.loc[data['is_mod_message'], 'side'] = 'Moderator'

# Display the first few rows of the updated DataFrame
print(data.head())

# Optionally, save the cleaned DataFrame to a new CSV file
# data.to_csv("cleaned_dataset.csv", index=False)

   Unnamed: 0  \
0           1
1           4
2           6
3           7
4           9

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 self_text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Because Israel will kill everyone inside? We were not discussing Gaza, but claiming Hamas is a threat to Gaza because you will genocide everyone to in there is maybe not such a good position to take.
1  Good for you, and boo on your friends/acquaintances!\n\nThe plain fact is that there are like 15million people in Israel, Gaza, and the West Bank.  2/3s of them are Israeli.  They aren't Russian, or American, or Arab, or Turkish, or Egyptian, or Etheopian, or French, or German, or or or...they're Israeli.  There isn't anywhere for Israelis to go but Israel, because it isn't a colonial state, it is a country all its own and it will fight, and kill, and imprison others to secure its continued existence.  The other 1/3 of people in that region are what most people would like to be Palestinians, living in Palestine.\n\nWe can disagree and discuss many things without fully agreeing - on what the borders of Palestine should be.  On facets of how IDF is prosecuting the war in Gaza, or how it handles security in the West Bank.  On facets of settlements and settler violence issues.  On many things.\n\nBut the root cause of this conflict, and the thing that cannot be disagreed about if there is ever going to be peace without genocide, is one simple fact:  Israel exists, and its people aren't going to allow that to change.  Refusing to talk to an Israeli is a tacit refusal to agree to that foundational fact, and it perpetuates conflict.  \n\nAgain, good for you!
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   A Gaza-West Bank corridor has been a part of every Israeli and Palestinian proposal for many years, it is not a seriously debated thing. And I should flippantly ask: why is having your country split in half bad? Is that something the Palestinians should be worried about?\n\nI mean, really. Saying your a controlled access highway would infringe on your rights while you're literally splitting up the WB into bantustans (with checkpoints!) is very funny.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       They'll definitely try after the war ends, and Israel might not be able to maintain a presence in Lebanon forever.
4                                                                                                             Hamas is an ideologically motivated militant group. It is motivated by religious animus, Palestinian nationalism and historical grievances. Whether you consider it a terror group is for you to decide, but the attack on October 7 plainly did not make many attempts to distinguish between legitimate combatants and civilians (one of the reasons everyone has forgotten about this terror attack is because Israel has done it nearly a hundred times over, since). The purpose of the attack did not have a military objective of "destroying Israel" in any meaningful sense of the word because the captives were quickly spirited away and they left only a token force to delay the Israelis.\n\nIn 48, the Arab League was obviously attempting to prevent the formation of Israel, they had a real army and invaded. In 67 the Arab League did not attack Israel, it was attacked, so I imagine their motivation was less aggressive than in 48. Did you mean 73?\n\nIran has been a week away from creating a bomb (according to Israel) for the last 10 years lmao. Israel could not force a regime change on Iran. How would they do it? By engaging in purely an air campaign against Iran?

         subreddit         created_time    author_name    post_created_time  \
0  IsraelPalestine  2025-04-27 23:58:56  MrNewVegas123  2025-04-27 09:42:09
1  IsraelPalestine  2025-04-27 23:56:51   cloudedknife  2025-04-27 21:39:55
2  IsraelPalestine  2025-04-27 23:55:23  MrNewVegas123  2025-04-27 13:40:05
3  IsraelPalestine  2025-04-27 23:54:50  ZachorMizrahi  2025-04-26 17:23:37
4  IsraelPalestine  2025-04-27 23:53:14  MrNewVegas123  2025-04-27 09:42:09

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         clean_text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Because Israel will kill everyone inside? We were not discussing Gaza, but claiming Hamas is a threat to Gaza because you will genocide everyone to in there is maybe not such a good position to take.
1  Good for you, and boo on your friends/acquaintances! The plain fact is that there are like 15million people in Israel, Gaza, and the West Bank. 2/3s of them are Israeli. They aren't Russian, or American, or Arab, or Turkish, or Egyptian, or Etheopian, or French, or German, or or or...they're Israeli. There isn't anywhere for Israelis to go but Israel, because it isn't a colonial state, it is a country all its own and it will fight, and kill, and imprison others to secure its continued existence. The other 1/3 of people in that region are what most people would like to be Palestinians, living in Palestine. We can disagree and discuss many things without fully agreeing - on what the borders of Palestine should be. On facets of how IDF is prosecuting the war in Gaza, or how it handles security in the West Bank. On facets of settlements and settler violence issues. On many things. But the root cause of this conflict, and the thing that cannot be disagreed about if there is ever going to be peace without genocide, is one simple fact: Israel exists, and its people aren't going to allow that to change. Refusing to talk to an Israeli is a tacit refusal to agree to that foundational fact, and it perpetuates conflict. Again, good for you!
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               A Gaza-West Bank corridor has been a part of every Israeli and Palestinian proposal for many years, it is not a seriously debated thing. And I should flippantly ask: why is having your country split in half bad? Is that something the Palestinians should be worried about? I mean, really. Saying your a controlled access highway would infringe on your rights while you're literally splitting up the WB into bantustans (with checkpoints!) is very funny.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                They'll definitely try after the war ends, and Israel might not be able to maintain a presence in Lebanon forever.
4                                                                                            Hamas is an ideologically motivated militant group. It is motivated by religious animus, Palestinian nationalism and historical grievances. Whether you consider it a terror group is for you to decide, but the attack on October 7 plainly did not make many attempts to distinguish between legitimate combatants and civilians (one of the reasons everyone has forgotten about this terror attack is because Israel has done it nearly a hundred times over, since). The purpose of the attack did not have a military objective of "destroying Israel" in any meaningful sense of the word because the captives were quickly spirited away and they left only a token force to delay the Israelis. In 48, the Arab League was obviously attempting to prevent the formation of Israel, they had a real army and invaded. In 67 the Arab League did not attack Israel, it was attacked, so I imagine their motivation was less aggressive than in 48. Did you mean 73? Iran has been a week away from creating a bomb (according to Israel) for the last 10 years lmao. Israel could not force a regime change on Iran. How would they do it? By engaging in purely an air campaign against Iran?

        side sentiment  is_mod_message
0  Palestine  Negative           False
1  Palestine  Negative           False
2  Palestine  Negative           False
3     Israel  Negative           False
4    Neutral  Negative           False

In [14]:
# Set the maximum column width to None to show full text
pd.set_option('display.max_colwidth', None)
filtered_df = data[data["clean_text"].str.contains("Fuck Israel")]
filtered_df.head()

,Unnamed: 0,self_text,subreddit,created_time,author_name,post_created_time,clean_text,side,sentiment,is_mod_message
4119,9929,Fuck Israel and all its supporters 🖕🏻🖕🏻🖕🏻🖕🏻,PublicFreakout,2025-04-24 02:09:59,spicytinyghost,2025-04-23 23:31:19,Fuck Israel and all its supporters 🖕🏻🖕🏻🖕🏻🖕🏻,Palestine,Negative,False
4160,10052,Fuck Israel,PublicFreakout,2025-04-24 01:19:03,Macho_Ric_Hogan,2025-04-23 23:31:19,Fuck Israel,Palestine,Negative,False
7539,18627,Fuck Israel,PublicFreakout,2025-04-21 01:37:43,Macho_Ric_Hogan,2025-04-20 13:46:04,Fuck Israel,Palestine,Negative,False
8209,20281,Fuck Israel,PublicFreakout,2025-04-20 15:20:13,Goomancy,2025-04-20 13:46:04,Fuck Israel,Palestine,Negative,False
8220,20311,Fuck Israel,PublicFreakout,2025-04-20 15:08:38,ArcHacks,2025-04-20 13:46:04,Fuck Israel,Palestine,Negative,False

In [15]:
# Delete moderator side, because it from BOT
data = data[data['side'] != 'Moderator'].reset_index(drop=True)

# Display the updated DataFrame
data.head()

,Unnamed: 0,self_text,subreddit,created_time,author_name,post_created_time,clean_text,side,sentiment,is_mod_message
0,1,"Because Israel will kill everyone inside? We were not discussing Gaza, but claiming Hamas is a threat to Gaza because you will genocide everyone to in there is maybe not such a good position to take.",IsraelPalestine,2025-04-27 23:58:56,MrNewVegas123,2025-04-27 09:42:09,"Because Israel will kill everyone inside? We were not discussing Gaza, but claiming Hamas is a threat to Gaza because you will genocide everyone to in there is maybe not such a good position to take.",Palestine,Negative,False
1,4,"Good for you, and boo on your friends/acquaintances!\n\nThe plain fact is that there are like 15million people in Israel, Gaza, and the West Bank. 2/3s of them are Israeli. They aren't Russian, or American, or Arab, or Turkish, or Egyptian, or Etheopian, or French, or German, or or or...they're Israeli. There isn't anywhere for Israelis to go but Israel, because it isn't a colonial state, it is a country all its own and it will fight, and kill, and imprison others to secure its continued existence. The other 1/3 of people in that region are what most people would like to be Palestinians, living in Palestine.\n\nWe can disagree and discuss many things without fully agreeing - on what the borders of Palestine should be. On facets of how IDF is prosecuting the war in Gaza, or how it handles security in the West Bank. On facets of settlements and settler violence issues. On many things.\n\nBut the root cause of this conflict, and the thing that cannot be disagreed about if there is ever going to be peace without genocide, is one simple fact: Israel exists, and its people aren't going to allow that to change. Refusing to talk to an Israeli is a tacit refusal to agree to that foundational fact, and it perpetuates conflict. \n\nAgain, good for you!",IsraelPalestine,2025-04-27 23:56:51,cloudedknife,2025-04-27 21:39:55,"Good for you, and boo on your friends/acquaintances! The plain fact is that there are like 15million people in Israel, Gaza, and the West Bank. 2/3s of them are Israeli. They aren't Russian, or American, or Arab, or Turkish, or Egyptian, or Etheopian, or French, or German, or or or...they're Israeli. There isn't anywhere for Israelis to go but Israel, because it isn't a colonial state, it is a country all its own and it will fight, and kill, and imprison others to secure its continued existence. The other 1/3 of people in that region are what most people would like to be Palestinians, living in Palestine. We can disagree and discuss many things without fully agreeing - on what the borders of Palestine should be. On facets of how IDF is prosecuting the war in Gaza, or how it handles security in the West Bank. On facets of settlements and settler violence issues. On many things. But the root cause of this conflict, and the thing that cannot be disagreed about if there is ever going to be peace without genocide, is one simple fact: Israel exists, and its people aren't going to allow that to change. Refusing to talk to an Israeli is a tacit refusal to agree to that foundational fact, and it perpetuates conflict. Again, good for you!",Palestine,Negative,False
2,6,"A Gaza-West Bank corridor has been a part of every Israeli and Palestinian proposal for many years, it is not a seriously debated thing. And I should flippantly ask: why is having your country split in half bad? Is that something the Palestinians should be worried about?\n\nI mean, really. Saying your a controlled access highway would infringe on your rights while you're literally splitting up the WB into bantustans (with checkpoints!) is very funny.",IsraelPalestine,2025-04-27 23:55:23,MrNewVegas123,2025-04-27 13:40:05,"A Gaza-West Bank corridor has been a part of every Israeli and Palestinian proposal for many years, it is not a seriously debated thing. And I should flippantly ask: why is having your country split in half bad? Is that something the Palestinians should be worried about? I mean, really. Saying your a controlled access highway would infringe on your rights while you're literally splitting up the WB into bantustans (with checkpoints!) is very funny.",Palestine,Negative,False
3,7,"They'll definitely try after the war ends, and Israel might not be able to maintain a presence in Lebanon forever.",IsraelPalestine,2025-04-27 23:54:50,ZachorMizrahi,2025-04-26 17:23:37,"They'll definitely try after the war ends, and Israel might not be able to maintain a presence in Lebanon forever.",Israel,Negative,False
4,9,"Hamas is an ideologically motivated militant group. It is motivated by religious animus, Palestinian nationalism and historical grievances. Whether you consider it a terror group is for you to decide, but the attack on October 7 plainly did not make many attempts to distinguish between legitimate combatants and civilians (one of the reasons everyone has forgotten about this terror attack is because Israel has done it nearly a hundred times over, since). The purpose of the attack did not have a military objective of ""destroying Israel"" in any meaningful sense of the word because the captives were quickly spirited away and they left only a token force to delay the Israelis.\n\nIn 48, the Arab League was obviously attempting to prevent the formation of Israel, they had a real army and invaded. In 67 the Arab League did not attack Israel, it was attacked, so I imagine their motivation was less aggressive than in 48. Did you mean 73?\n\nIran has been a week away from creating a bomb (according to Israel) for the last 10 years lmao. Israel could not force a regime change on Iran. How would they do it? By engaging in purely an air campaign against Iran?",IsraelPalestine,2025-04-27 23:53:14,MrNewVegas123,2025-04-27 09:42:09,"Hamas is an ideologically motivated militant group. It is motivated by religious animus, Palestinian nationalism and historical grievances. Whether you consider it a terror group is for you to decide, but the attack on October 7 plainly did not make many attempts to distinguish between legitimate combatants and civilians (one of the reasons everyone has forgotten about this terror attack is because Israel has done it nearly a hundred times over, since). The purpose of the attack did not have a military objective of ""destroying Israel"" in any meaningful sense of the word because the captives were quickly spirited away and they left only a token force to delay the Israelis. In 48, the Arab League was obviously attempting to prevent the formation of Israel, they had a real army and invaded. In 67 the Arab League did not attack Israel, it was attacked, so I imagine their motivation was less aggressive than in 48. Did you mean 73? Iran has been a week away from creating a bomb (according to Israel) for the last 10 years lmao. Israel could not force a regime change on Iran. How would they do it? By engaging in purely an air campaign against Iran?",Neutral,Negative,False

In [16]:
data = data.drop("is_mod_message", axis=1)
data = data.drop("post_created_time", axis=1)
data.to_csv('final_dataset_israel-palestine.csv', index=False)

In [17]:
data.head()

,Unnamed: 0,self_text,subreddit,created_time,author_name,clean_text,side,sentiment
0,1,"Because Israel will kill everyone inside? We were not discussing Gaza, but claiming Hamas is a threat to Gaza because you will genocide everyone to in there is maybe not such a good position to take.",IsraelPalestine,2025-04-27 23:58:56,MrNewVegas123,"Because Israel will kill everyone inside? We were not discussing Gaza, but claiming Hamas is a threat to Gaza because you will genocide everyone to in there is maybe not such a good position to take.",Palestine,Negative
1,4,"Good for you, and boo on your friends/acquaintances!\n\nThe plain fact is that there are like 15million people in Israel, Gaza, and the West Bank. 2/3s of them are Israeli. They aren't Russian, or American, or Arab, or Turkish, or Egyptian, or Etheopian, or French, or German, or or or...they're Israeli. There isn't anywhere for Israelis to go but Israel, because it isn't a colonial state, it is a country all its own and it will fight, and kill, and imprison others to secure its continued existence. The other 1/3 of people in that region are what most people would like to be Palestinians, living in Palestine.\n\nWe can disagree and discuss many things without fully agreeing - on what the borders of Palestine should be. On facets of how IDF is prosecuting the war in Gaza, or how it handles security in the West Bank. On facets of settlements and settler violence issues. On many things.\n\nBut the root cause of this conflict, and the thing that cannot be disagreed about if there is ever going to be peace without genocide, is one simple fact: Israel exists, and its people aren't going to allow that to change. Refusing to talk to an Israeli is a tacit refusal to agree to that foundational fact, and it perpetuates conflict. \n\nAgain, good for you!",IsraelPalestine,2025-04-27 23:56:51,cloudedknife,"Good for you, and boo on your friends/acquaintances! The plain fact is that there are like 15million people in Israel, Gaza, and the West Bank. 2/3s of them are Israeli. They aren't Russian, or American, or Arab, or Turkish, or Egyptian, or Etheopian, or French, or German, or or or...they're Israeli. There isn't anywhere for Israelis to go but Israel, because it isn't a colonial state, it is a country all its own and it will fight, and kill, and imprison others to secure its continued existence. The other 1/3 of people in that region are what most people would like to be Palestinians, living in Palestine. We can disagree and discuss many things without fully agreeing - on what the borders of Palestine should be. On facets of how IDF is prosecuting the war in Gaza, or how it handles security in the West Bank. On facets of settlements and settler violence issues. On many things. But the root cause of this conflict, and the thing that cannot be disagreed about if there is ever going to be peace without genocide, is one simple fact: Israel exists, and its people aren't going to allow that to change. Refusing to talk to an Israeli is a tacit refusal to agree to that foundational fact, and it perpetuates conflict. Again, good for you!",Palestine,Negative
2,6,"A Gaza-West Bank corridor has been a part of every Israeli and Palestinian proposal for many years, it is not a seriously debated thing. And I should flippantly ask: why is having your country split in half bad? Is that something the Palestinians should be worried about?\n\nI mean, really. Saying your a controlled access highway would infringe on your rights while you're literally splitting up the WB into bantustans (with checkpoints!) is very funny.",IsraelPalestine,2025-04-27 23:55:23,MrNewVegas123,"A Gaza-West Bank corridor has been a part of every Israeli and Palestinian proposal for many years, it is not a seriously debated thing. And I should flippantly ask: why is having your country split in half bad? Is that something the Palestinians should be worried about? I mean, really. Saying your a controlled access highway would infringe on your rights while you're literally splitting up the WB into bantustans (with checkpoints!) is very funny.",Palestine,Negative
3,7,"They'll definitely try after the war ends, and Israel might not be able to maintain a presence in Lebanon forever.",IsraelPalestine,2025-04-27 23:54:50,ZachorMizrahi,"They'll definitely try after the war ends, and Israel might not be able to maintain a presence in Lebanon forever.",Israel,Negative
4,9,"Hamas is an ideologically motivated militant group. It is motivated by religious animus, Palestinian nationalism and historical grievances. Whether you consider it a terror group is for you to decide, but the attack on October 7 plainly did not make many attempts to distinguish between legitimate combatants and civilians (one of the reasons everyone has forgotten about this terror attack is because Israel has done it nearly a hundred times over, since). The purpose of the attack did not have a military objective of ""destroying Israel"" in any meaningful sense of the word because the captives were quickly spirited away and they left only a token force to delay the Israelis.\n\nIn 48, the Arab League was obviously attempting to prevent the formation of Israel, they had a real army and invaded. In 67 the Arab League did not attack Israel, it was attacked, so I imagine their motivation was less aggressive than in 48. Did you mean 73?\n\nIran has been a week away from creating a bomb (according to Israel) for the last 10 years lmao. Israel could not force a regime change on Iran. How would they do it? By engaging in purely an air campaign against Iran?",IsraelPalestine,2025-04-27 23:53:14,MrNewVegas123,"Hamas is an ideologically motivated militant group. It is motivated by religious animus, Palestinian nationalism and historical grievances. Whether you consider it a terror group is for you to decide, but the attack on October 7 plainly did not make many attempts to distinguish between legitimate combatants and civilians (one of the reasons everyone has forgotten about this terror attack is because Israel has done it nearly a hundred times over, since). The purpose of the attack did not have a military objective of ""destroying Israel"" in any meaningful sense of the word because the captives were quickly spirited away and they left only a token force to delay the Israelis. In 48, the Arab League was obviously attempting to prevent the formation of Israel, they had a real army and invaded. In 67 the Arab League did not attack Israel, it was attacked, so I imagine their motivation was less aggressive than in 48. Did you mean 73? Iran has been a week away from creating a bomb (according to Israel) for the last 10 years lmao. Israel could not force a regime change on Iran. How would they do it? By engaging in purely an air campaign against Iran?",Neutral,Negative

In [3]:
df1 = pd.read_csv("final_dataset_israel-palestine.csv")
df1.head()

,Unnamed: 0,self_text,subreddit,created_time,author_name,clean_text,side,sentiment
0,1,Because Israel will kill everyone inside? We w...,IsraelPalestine,2025-04-27 23:58:56,MrNewVegas123,Because Israel will kill everyone inside? We w...,Palestine,Negative
1,4,"Good for you, and boo on your friends/acquaint...",IsraelPalestine,2025-04-27 23:56:51,cloudedknife,"Good for you, and boo on your friends/acquaint...",Palestine,Negative
2,6,A Gaza-West Bank corridor has been a part of e...,IsraelPalestine,2025-04-27 23:55:23,MrNewVegas123,A Gaza-West Bank corridor has been a part of e...,Palestine,Negative
3,7,"They'll definitely try after the war ends, and...",IsraelPalestine,2025-04-27 23:54:50,ZachorMizrahi,"They'll definitely try after the war ends, and...",Israel,Negative
4,9,Hamas is an ideologically motivated militant g...,IsraelPalestine,2025-04-27 23:53:14,MrNewVegas123,Hamas is an ideologically motivated militant g...,Neutral,Negative

In [4]:
len(df1.drop_duplicates()) / len(df1)

1.0

In [5]:
# Set the maximum column width to None to show full text
pd.set_option('display.max_colwidth', None)
filtered_df = df1[df1["sentiment"].str.contains("Neutral") & df1["side"].str.contains("Israel")]
filtered_df.head()

,Unnamed: 0,self_text,subreddit,created_time,author_name,clean_text,side,sentiment
13,36,"I stand corrected, there was a small protest. Still not anywhere near the scale of protests against Israel. The question is still there, why?",IsraelPalestine,2025-04-27 23:42:57,aqulushly,"I stand corrected, there was a small protest. Still not anywhere near the scale of protests against Israel. The question is still there, why?",Israel,Neutral
16,55,"Yeah, agreed. Neither Palestinians nor Israelis are inhuman monsters. They can live alongside one another in peace...\n\nWhich is why I think Palestinian right of return is fair and just.",IsraelPalestine,2025-04-27 23:32:05,SilasRhodes,"Yeah, agreed. Neither Palestinians nor Israelis are inhuman monsters. They can live alongside one another in peace... Which is why I think Palestinian right of return is fair and just.",Israel,Neutral
29,124,"Say, ˹O Prophet,˺ “If the ˹eternal˺ Home of the Hereafter with Allah is exclusively for you ˹Israelites˺ out of all humanity, then wish for death if what you say is true!”{94} But they will never wish for that because of what their hands have done.And Allah has ˹perfect˺ knowledge of the wrongdoers.{95} You will surely find them clinging to life more eagerly than any other people, even more than polytheists. Each one of them wishes to live a thousand years. But even if they were to live that long, it would not save them from the punishment. And Allah is All-Seeing of what they do.{96}\n\nSurat Al Baqara.",Palestine,2025-04-27 23:03:15,librephili,"Say, ˹O Prophet,˺ “If the ˹eternal˺ Home of the Hereafter with Allah is exclusively for you ˹Israelites˺ out of all humanity, then wish for death if what you say is true!”{94} But they will never wish for that because of what their hands have done.And Allah has ˹perfect˺ knowledge of the wrongdoers.{95} You will surely find them clinging to life more eagerly than any other people, even more than polytheists. Each one of them wishes to live a thousand years. But even if they were to live that long, it would not save them from the punishment. And Allah is All-Seeing of what they do.{96} Surat Al Baqara.",Israel,Neutral
30,125,What makes you think that will give? I'm very curious; it seems like Israel's position is stronger than ever.,IsraelPalestine,2025-04-27 23:02:50,yusuf_mizrah,What makes you think that will give? I'm very curious; it seems like Israel's position is stronger than ever.,Israel,Neutral
41,152,"Both sides have a huge set of similarities they could build off of.\n\nIf we simply were against acts (like “murdering children”) regardless of who commits them, we would all agree. I think anyone killing children without remorse is a terrorist, regardless of what religion the child or the murderer is. I have found that framing it this way allows you to very quickly identify who the fans of genocide are versus anyone with redeemable hope.\n\nFor what it’s worth, this conflict has been tough for me and a lot of my Jewish and Israeli friends as well, but dialogue and understanding and learning and growing is the only way forward since this is a region we will all call home for a long time to come inshallah (and b’ezrat Hashem).",IsraelPalestine,2025-04-27 22:49:19,ThirstyTarantulas,"Both sides have a huge set of similarities they could build off of. If we simply were against acts (like “murdering children”) regardless of who commits them, we would all agree. I think anyone killing children without remorse is a terrorist, regardless of what religion the child or the murderer is. I have found that framing it this way allows you to very quickly identify who the fans of genocide are versus anyone with redeemable hope. For what it’s worth, this conflict has been tough for me and a lot of my Jewish and Israeli friends as well, but dialogue and understanding and learning and growing is the only way forward since this is a region we will all call home for a long time to come inshallah (and b’ezrat Hashem).",Israel,Neutral

> ### it can be, the user choose one side but the sentiment is neutral!

**1. Neutral Sentiment + Palestine Side**

“Palestinian children need more access to education.”
→ Talks about Palestine, but it’s factual and not emotionally charged.

**2. Neutral Sentiment + Israel Side**

“The Israeli government passed a new law today.”
→ Involves Israel, but no sentiment — it’s just information.

**3. Neutral Sentiment + Neutral Side**

“Both parties are in ongoing negotiations.”
→ Balanced and fact-driven, no emotional tone or bias.

In [20]:
first_created_time = data['created_time'].min()
last_created_time = data['created_time'].max()

print ('First created time is',first_created_time,'and The last created time is', last_created_time)

First created time is 2025-01-20 13:03:56 and The last created time is 2025-04-27 23:58:56